name: linter
on:
  # Can be manually triggered
  workflow_dispatch: {}
  # Triggered on each pull request to main
  pull_request:
    branches: [ main ]
env:
  SNOWFLAKE_DATABASE: warehouse
  SNOWFLAKE_WAREHOUSE: xsmall_wh
  SNOWFLAKE_ROLE: accountadmin
  SNOWFLAKE_SCHEMA: raw
  S3_URL: s3://snowflakes333/GTFS
  SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository in agent
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      # https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Run linting checks. Exit code 1 if linter failed
        run: |
          bash ./.github/bin/linter.sh
