sources:
  - name: GTFS
    database: warehouse
    schema: raw
    tables:
      - name: raw_agency
        meta:
          dagster:
            asset_key: ["raw_agency"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_calendar
        meta:
          dagster:
            asset_key: ["raw_calendar"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_calendar_dates
        meta:
          dagster:
            asset_key: ["raw_calendar_dates"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_routes
        meta:
          dagster:
            asset_key: ["raw_routes"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_stop_times
        meta:
          dagster:
            asset_key: ["raw_stop_times"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_stops
        meta:
          dagster:
            asset_key: ["raw_stops"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_trips
        meta:
          dagster:
            asset_key: ["raw_trips"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: raw_shapes
        meta:
         dagster:
           asset_key: ["raw_shapes"] # This metadata specifies the corresponding Dagster asset for this dbt source.
  - name: api
    database: warehouse
    schema: raw
    tables:
      - name: vehicle_monitor_parsed
        meta:
          dagster:
            asset_key: ["vehicle_monitor_parsed"] # This metadata specifies the corresponding Dagster asset for this dbt source.
  